name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
            with:
              username: j96108q7_compreg
              host: j96108q7.beget.tech
              password: Dn100883!
              script: 'cd /home/j/j96108q7/compreg && ./deployer.sh'

