name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          username: j96108q7_compreg
          host: j96108q7.beget.tech
          password: Dn100883!
          script: 'cd /home/j/j96108q7/compreg && ./deployer.sh'

      - uses: actions/checkout@v3
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
